<?php

use App\Models\Banco;
use Illuminate\Database\Seeder;

class BancoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $bancos = [
            ['codigo_banco' => '001', 'nome' => 'Banco do Brasil S/A'],
            ['codigo_banco' => '002', 'nome' => 'Banco Central do Brasil'],
            ['codigo_banco' => '003', 'nome' => 'Banco da Amazonia S/A'],
            ['codigo_banco' => '004', 'nome' => 'Banco do Nordeste do Brasil S/A'],
            ['codigo_banco' => '007', 'nome' => 'Banco Nac Desenv. Eco. Social S/A'],
            ['codigo_banco' => '008', 'nome' => 'Banco Meridional do Brasil'],
            ['codigo_banco' => '020', 'nome' => 'Banco do Estado de Alagoas S/A'],
            ['codigo_banco' => '021', 'nome' => 'Banco do Estado do Espirito Santo S/A'],
            ['codigo_banco' => '022', 'nome' => 'Banco de Credito Real de Minas Gerais S/A],'],
            ['codigo_banco' => '024', 'nome' => 'Banco do Estado de Pernambuco'],
            ['codigo_banco' => '025', 'nome' => 'Banco Alfa S/A'],
            ['codigo_banco' => '026', 'nome' => 'Banco do Estado do Acre S/A'],
            ['codigo_banco' => '027', 'nome' => 'Banco do Estado de Santa Catarina S/A'],
            ['codigo_banco' => '028', 'nome' => 'Banco do Estado da Bahia S/A'],
            ['codigo_banco' => '029', 'nome' => 'Banco do Estado do Rio de Janeiro S/A'],
            ['codigo_banco' => '030', 'nome' => 'Banco do Estado da Paraiba S/A'],
            ['codigo_banco' => '031', 'nome' => 'Banco do Estado de Goias S/A'],
            ['codigo_banco' => '032', 'nome' => 'Banco do Estado do Mato Grosso S/A.'],
            ['codigo_banco' => '033', 'nome' => 'Banco do Estado de Sao Paulo S/A'],
            ['codigo_banco' => '034', 'nome' => 'Banco do Estado do Amazonas S/A'],
            ['codigo_banco' => '035', 'nome' => 'Banco do Estado do Ceara S/A'],
            ['codigo_banco' => '036', 'nome' => 'Banco do Estado do Maranhao S/A'],
            ['codigo_banco' => '037', 'nome' => 'Banco do Estado do Para S/A'],
            ['codigo_banco' => '038', 'nome' => 'Banco do Estado do Parana S/A'],
            ['codigo_banco' => '039', 'nome' => 'Banco do Estado do Piaui S/A'],
            ['codigo_banco' => '041', 'nome' => 'Banco do Estado do Rio Grande do Sul S/A'],
            ['codigo_banco' => '047', 'nome' => 'Banco do Estado de Sergipe S/A'],
            ['codigo_banco' => '048', 'nome' => 'Banco do Estado de Minas Gerais S/A'],
            ['codigo_banco' => '059', 'nome' => 'Banco do Estado de Rondonia S/A'],
            ['codigo_banco' => '070', 'nome' => 'Banco de Brasilia S/A'],
            ['codigo_banco' => '104', 'nome' => 'Caixa Economica Federal'],
            ['codigo_banco' => '106', 'nome' => 'Banco Itabanco S/A.'],
            ['codigo_banco' => '107', 'nome' => 'Banco BBM S/A'],
            ['codigo_banco' => '109', 'nome' => 'Banco Credibanco S/A'],
            ['codigo_banco' => '116', 'nome' => 'Banco B.N.L do Brasil S/A'],
            ['codigo_banco' => '148', 'nome' => 'Multi Banco S/A'],
            ['codigo_banco' => '151', 'nome' => 'Caixa Economica do Estado de Sao Paulo'],
            ['codigo_banco' => '153', 'nome' => 'Caixa Economica do Estado do R.G.Sul'],
            ['codigo_banco' => '165', 'nome' => 'Banco Norchem S/A'],
            ['codigo_banco' => '166', 'nome' => 'Banco Inter-Atlantico S/A'],
            ['codigo_banco' => '168', 'nome' => 'Banco C.C.F. Brasil S/A'],
            ['codigo_banco' => '175', 'nome' => 'Continental Banco S/A'],
            ['codigo_banco' => '184', 'nome' => 'BBA - Creditanstalt S/A'],
            ['codigo_banco' => '199', 'nome' => 'Banco Financial Portugues'],
            ['codigo_banco' => '200', 'nome' => 'Banco Fricrisa Axelrud S/A'],
            ['codigo_banco' => '201', 'nome' => 'Banco Augusta Industria E Comercial S/A'],
            ['codigo_banco' => '204', 'nome' => 'Banco S.R.L S/A'],
            ['codigo_banco' => '205', 'nome' => 'Banco Sul America S/A'],
            ['codigo_banco' => '206', 'nome' => 'Banco Martinelli S/A'],
            ['codigo_banco' => '208', 'nome' => 'Banco Pactual S/A'],
            ['codigo_banco' => '210', 'nome' => 'Deutsch Sudamerikaniche Bank Ag'],
            ['codigo_banco' => '211', 'nome' => 'Banco Sistema S/A'],
            ['codigo_banco' => '212', 'nome' => 'Banco Matone S/A'],
            ['codigo_banco' => '213', 'nome' => 'Banco Arbi S/A'],
            ['codigo_banco' => '214', 'nome' => 'Banco Dibens S/A'],
            ['codigo_banco' => '215', 'nome' => 'Banco America do Sul S/A'],
            ['codigo_banco' => '216', 'nome' => 'Banco Regional Malcon S/A'],
            ['codigo_banco' => '217', 'nome' => 'Banco Agroinvest S/A'],
            ['codigo_banco' => '218', 'nome' => 'BBS - Banco Bonsucesso S/A.'],
            ['codigo_banco' => '219', 'nome' => 'Banco de Credito de Sao Paulo S/A'],
            ['codigo_banco' => '220', 'nome' => 'Banco Crefisul'],
            ['codigo_banco' => '221', 'nome' => 'Banco Graphus S/A'],
            ['codigo_banco' => '222', 'nome' => 'Banco Agf Brasil S. A.'],
            ['codigo_banco' => '223', 'nome' => 'Banco Interunion S/A'],
            ['codigo_banco' => '224', 'nome' => 'Banco Fibra S/A'],
            ['codigo_banco' => '225', 'nome' => 'Banco Brascan S/A'],
            ['codigo_banco' => '228', 'nome' => 'Banco Icatu S/A'],
            ['codigo_banco' => '229', 'nome' => 'Banco Cruzeiro S/A'],
            ['codigo_banco' => '230', 'nome' => 'Banco Bandeirantes S/A'],
            ['codigo_banco' => '231', 'nome' => 'Banco Boavista S/A'],
            ['codigo_banco' => '232', 'nome' => 'Banco Interpart S/A'],
            ['codigo_banco' => '233', 'nome' => 'Banco Mappin S/A'],
            ['codigo_banco' => '234', 'nome' => 'Banco Lavra S/A.'],
            ['codigo_banco' => '235', 'nome' => 'Banco Liberal S/A'],
            ['codigo_banco' => '236', 'nome' => 'Banco Cambial S/A'],
            ['codigo_banco' => '237', 'nome' => 'Banco Bradesco S/A'],
            ['codigo_banco' => '239', 'nome' => 'Banco Bancred S/A'],
            ['codigo_banco' => '240', 'nome' => 'Banco de Credito Real de Minas Gerais S.'],
            ['codigo_banco' => '241', 'nome' => 'Banco Classico S/A'],
            ['codigo_banco' => '242', 'nome' => 'Banco Euroinvest S/A'],
            ['codigo_banco' => '243', 'nome' => 'Banco Stock S/A'],
            ['codigo_banco' => '244', 'nome' => 'Banco Cidade S/A'],
            ['codigo_banco' => '245', 'nome' => 'Banco Empresarial S/A'],
            ['codigo_banco' => '246', 'nome' => 'Banco ABC Roma S/A'],
            ['codigo_banco' => '247', 'nome' => 'Banco Omega S/A'],
            ['codigo_banco' => '249', 'nome' => 'Banco Investcred S/A'],
            ['codigo_banco' => '250', 'nome' => 'Banco Schahin Cury S/A'],
            ['codigo_banco' => '251', 'nome' => 'Banco Sao Jorge S/A.'],
            ['codigo_banco' => '252', 'nome' => 'Banco Fininvest S/A'],
            ['codigo_banco' => '254', 'nome' => 'Banco Parana Banco S/A'],
            ['codigo_banco' => '255', 'nome' => 'Milbanco S/A.'],
            ['codigo_banco' => '256', 'nome' => 'Banco Gulvinvest S/A'],
            ['codigo_banco' => '258', 'nome' => 'Banco Induscred S/A'],
            ['codigo_banco' => '261', 'nome' => 'Banco Varig S/A'],
            ['codigo_banco' => '262', 'nome' => 'Banco Boreal S/A'],
            ['codigo_banco' => '263', 'nome' => 'Banco Cacique'],
            ['codigo_banco' => '264', 'nome' => 'Banco Performance S/A'],
            ['codigo_banco' => '265', 'nome' => 'Banco Fator S/A'],
            ['codigo_banco' => '266', 'nome' => 'Banco Cedula S/A'],
            ['codigo_banco' => '267', 'nome' => 'Banco Bbm-Com.C.Imob.Cfi S/A.'],
            ['codigo_banco' => '275', 'nome' => 'Banco Real S/A'],
            ['codigo_banco' => '277', 'nome' => 'Banco Planibanc S/A'],
            ['codigo_banco' => '282', 'nome' => 'Banco Brasileiro Comercial'],
            ['codigo_banco' => '291', 'nome' => 'Banco de Credito Nacional S/A'],
            ['codigo_banco' => '294', 'nome' => 'BCR - Banco de Credito Real S/A'],
            ['codigo_banco' => '295', 'nome' => 'Banco Crediplan S/A'],
            ['codigo_banco' => '300', 'nome' => 'Banco de La Nacion Argentina S/A'],
            ['codigo_banco' => '302', 'nome' => 'Banco do Progresso S/A'],
            ['codigo_banco' => '303', 'nome' => 'Banco HNF S/A.'],
            ['codigo_banco' => '304', 'nome' => 'Banco Pontual S/A'],
            ['codigo_banco' => '308', 'nome' => 'Banco Comercial Bancesa S/A.'],
            ['codigo_banco' => '318', 'nome' => 'Banco B.M.G. S/A'],
            ['codigo_banco' => '320', 'nome' => 'Banco Industrial E Comercial'],
            ['codigo_banco' => '341', 'nome' => 'Banco Itau S/A'],
            ['codigo_banco' => '346', 'nome' => 'Banco Frances E Brasileiro S/A'],
            ['codigo_banco' => '347', 'nome' => 'Banco Sudameris Brasil S/A'],
            ['codigo_banco' => '351', 'nome' => 'Banco Bozano Simonsen S/A'],
            ['codigo_banco' => '353', 'nome' => 'Banco Geral do Comercio S/A'],
            ['codigo_banco' => '356', 'nome' => 'ABN AMRO S/A'],
            ['codigo_banco' => '366', 'nome' => 'Banco Sogeral S/A'],
            ['codigo_banco' => '369', 'nome' => 'Pontual'],
            ['codigo_banco' => '370', 'nome' => 'BEAL - Banco Europeu Para America Latina'],
            ['codigo_banco' => '372', 'nome' => 'Banco Itamarati S/A'],
            ['codigo_banco' => '375', 'nome' => 'Banco Fenicia S/A'],
            ['codigo_banco' => '376', 'nome' => 'Chase Manhattan Bank S/A'],
            ['codigo_banco' => '388', 'nome' => 'Banco Mercantil de Descontos S/A'],
            ['codigo_banco' => '389', 'nome' => 'Banco Mercantil do Brasil S/A'],
            ['codigo_banco' => '392', 'nome' => 'Banco Mercantil de Sao Paulo S/A'],
            ['codigo_banco' => '394', 'nome' => 'Banco B.M.C. S/A'],
            ['codigo_banco' => '399', 'nome' => 'Banco Bamerindus do Brasil S/A'],
            ['codigo_banco' => '409', 'nome' => 'Unibanco - Uniao Dos Bancos Brasileiros'],
            ['codigo_banco' => '412', 'nome' => 'Banco Nacional da Bahia S/A'],
            ['codigo_banco' => '415', 'nome' => 'Banco Nacional S/A'],
            ['codigo_banco' => '420', 'nome' => 'Banco Nacional do Norte S/A'],
            ['codigo_banco' => '422', 'nome' => 'Banco Safra S/A'],
            ['codigo_banco' => '424', 'nome' => 'Banco Noroeste S/A'],
            ['codigo_banco' => '434', 'nome' => 'Banco Fortaleza S/A'],
            ['codigo_banco' => '453', 'nome' => 'Banco Rural S/A'],
            ['codigo_banco' => '456', 'nome' => 'Banco Tokio S/A'],
            ['codigo_banco' => '464', 'nome' => 'Banco Sumitomo Brasileiro S/A'],
            ['codigo_banco' => '466', 'nome' => 'Banco Mitsubishi Brasileiro S/A'],
            ['codigo_banco' => '472', 'nome' => 'Lloyds Bank Plc'],
            ['codigo_banco' => '473', 'nome' => 'Banco Financial Portugues S/A'],
            ['codigo_banco' => '477', 'nome' => 'Citibank N.A'],
            ['codigo_banco' => '479', 'nome' => 'Banco de Boston S/A'],
            ['codigo_banco' => '480', 'nome' => 'Banco Portugues do Atlantico-Brasil S/A'],
            ['codigo_banco' => '483', 'nome' => 'Banco Agrimisa S/A.'],
            ['codigo_banco' => '487', 'nome' => 'Deutsche Bank S/A - Banco Alemao'],
            ['codigo_banco' => '488', 'nome' => 'Banco J. P. Morgan S/A'],
            ['codigo_banco' => '489', 'nome' => 'Banesto Banco Urugauay S/A'],
            ['codigo_banco' => '492', 'nome' => 'Internationale Nederlanden Bank N.V.'],
            ['codigo_banco' => '493', 'nome' => 'Banco Union S/A.C.A'],
            ['codigo_banco' => '494', 'nome' => 'Banco La Rep. Oriental Del Uruguay'],
            ['codigo_banco' => '495', 'nome' => 'Banco La Provincia de Buenos Aires'],
            ['codigo_banco' => '496', 'nome' => 'Banco Exterior de Espana S/A'],
            ['codigo_banco' => '498', 'nome' => 'Centro Hispano Banco'],
            ['codigo_banco' => '499', 'nome' => 'Banco Iochpe S/A'],
            ['codigo_banco' => '501', 'nome' => 'Banco Brasileiro Iraquiano S/A.'],
            ['codigo_banco' => '502', 'nome' => 'Banco Santander S/A'],
            ['codigo_banco' => '504', 'nome' => 'Banco Multiplic S/A'],
            ['codigo_banco' => '505', 'nome' => 'Banco Garantia S/A'],
            ['codigo_banco' => '600', 'nome' => 'Banco Luso Brasileiro S/A'],
            ['codigo_banco' => '601', 'nome' => 'Bfc Banco S/A.'],
            ['codigo_banco' => '602', 'nome' => 'Banco Patente S/A'],
            ['codigo_banco' => '604', 'nome' => 'Banco Industrial do Brasil S/A'],
            ['codigo_banco' => '607', 'nome' => 'Banco Santos Neves S/A'],
            ['codigo_banco' => '608', 'nome' => 'Banco Open S/A'],
            ['codigo_banco' => '610', 'nome' => 'Banco V.R. S/A'],
            ['codigo_banco' => '611', 'nome' => 'Banco Paulista S/A'],
            ['codigo_banco' => '612', 'nome' => 'Banco Guanabara S/A'],
            ['codigo_banco' => '613', 'nome' => 'Banco Pecunia S/A'],
            ['codigo_banco' => '616', 'nome' => 'Banco Interpacifico S/A'],
            ['codigo_banco' => '617', 'nome' => 'Banco Investor S/A.'],
            ['codigo_banco' => '618', 'nome' => 'Banco Tendencia S/A'],
            ['codigo_banco' => '621', 'nome' => 'Banco Aplicap S/A.'],
            ['codigo_banco' => '622', 'nome' => 'Banco Dracma S/A'],
            ['codigo_banco' => '623', 'nome' => 'Banco Panamericano S/A'],
            ['codigo_banco' => '624', 'nome' => 'Banco General Motors S/A'],
            ['codigo_banco' => '625', 'nome' => 'Banco Araucaria S/A'],
            ['codigo_banco' => '626', 'nome' => 'Banco Ficsa S/A'],
            ['codigo_banco' => '627', 'nome' => 'Banco Destak S/A'],
            ['codigo_banco' => '628', 'nome' => 'Banco Criterium S/A'],
            ['codigo_banco' => '629', 'nome' => 'Bancorp Banco Coml. E. de Investmento'],
            ['codigo_banco' => '630', 'nome' => 'Banco Intercap S/A'],
            ['codigo_banco' => '633', 'nome' => 'Banco Redimento S/A'],
            ['codigo_banco' => '634', 'nome' => 'Banco Triangulo S/A'],
            ['codigo_banco' => '635', 'nome' => 'Banco do Estado do Amapa S/A'],
            ['codigo_banco' => '637', 'nome' => 'Banco Sofisa S/A'],
            ['codigo_banco' => '638', 'nome' => 'Banco Prosper S/A'],
            ['codigo_banco' => '639', 'nome' => 'Big S/A. - Banco Irmaos Guimaraes'],
            ['codigo_banco' => '640', 'nome' => 'Banco de Credito Metropolitano S/A'],
            ['codigo_banco' => '641', 'nome' => 'Banco Excel Economico S/A'],
            ['codigo_banco' => '643', 'nome' => 'Banco Segmento S/A'],
            ['codigo_banco' => '645', 'nome' => 'Banco do Estado de Roraima S/A'],
            ['codigo_banco' => '647', 'nome' => 'Banco Marka S/A'],
            ['codigo_banco' => '648', 'nome' => 'Banco Atlantis S/A'],
            ['codigo_banco' => '649', 'nome' => 'Banco Dimensao S/A'],
            ['codigo_banco' => '650', 'nome' => 'Banco Pebb S/A'],
            ['codigo_banco' => '652', 'nome' => 'Banco Frances E Brasileiro S/A],'],
            ['codigo_banco' => '653', 'nome' => 'Banco Indusval S/A'],
            ['codigo_banco' => '654', 'nome' => 'Banco A. J. Renner S/A'],
            ['codigo_banco' => '655', 'nome' => 'Banco Votorantim S/A.'],
            ['codigo_banco' => '656', 'nome' => 'Banco Matrix S/A'],
            ['codigo_banco' => '657', 'nome' => 'Banco Tecnicorp S/A'],
            ['codigo_banco' => '658', 'nome' => 'Banco Porto Real S/A'],
            ['codigo_banco' => '702', 'nome' => 'Banco Santos S/A'],
            ['codigo_banco' => '705', 'nome' => 'Banco Investcorp S/A.'],
            ['codigo_banco' => '707', 'nome' => 'Banco Daycoval S/A'],
            ['codigo_banco' => '711', 'nome' => 'Banco Vetor S/A.'],
            ['codigo_banco' => '713', 'nome' => 'Banco Cindam S/A'],
            ['codigo_banco' => '715', 'nome' => 'Banco Vega S/A'],
            ['codigo_banco' => '718', 'nome' => 'Banco Operador S/A'],
            ['codigo_banco' => '719', 'nome' => 'Banco Primus S/A'],
            ['codigo_banco' => '720', 'nome' => 'Banco Maxinvest S/A'],
            ['codigo_banco' => '721', 'nome' => 'Banco Credibel S/A'],
            ['codigo_banco' => '722', 'nome' => 'Banco Interior de Sao Paulo S/A'],
            ['codigo_banco' => '724', 'nome' => 'Banco Porto Seguro S/A'],
            ['codigo_banco' => '725', 'nome' => 'Banco Finabanco S/A'],
            ['codigo_banco' => '726', 'nome' => 'Banco Universal S/A'],
            ['codigo_banco' => '728', 'nome' => 'Banco Fital S/A'],
            ['codigo_banco' => '729', 'nome' => 'Banco Fonte S/A'],
            ['codigo_banco' => '730', 'nome' => 'Banco Comercial Paraguayo S/A'],
            ['codigo_banco' => '731', 'nome' => 'Banco Gnpp S/A.'],
            ['codigo_banco' => '732', 'nome' => 'Banco Premier S/A.'],
            ['codigo_banco' => '733', 'nome' => 'Banco Nacoes S/A.'],
            ['codigo_banco' => '734', 'nome' => 'Banco Gerdau S/A'],
            ['codigo_banco' => '735', 'nome' => 'Banco Potencial'],
            ['codigo_banco' => '736', 'nome' => 'Banco United S/A'],
            ['codigo_banco' => '737', 'nome' => 'Theca'],
            ['codigo_banco' => '738', 'nome' => 'Marada'],
            ['codigo_banco' => '739', 'nome' => 'BGN'],
            ['codigo_banco' => '740', 'nome' => 'BCN Barclays'],
            ['codigo_banco' => '741', 'nome' => 'BRP'],
            ['codigo_banco' => '742', 'nome' => 'Equatorial'],
            ['codigo_banco' => '743', 'nome' => 'Banco Emblema S/A'],
            ['codigo_banco' => '744', 'nome' => 'The First National Bank Of Boston'],
            ['codigo_banco' => '745', 'nome' => 'Citiban N.A.'],
            ['codigo_banco' => '746', 'nome' => 'Modal S\A'],
            ['codigo_banco' => '747', 'nome' => 'Raibobank do Brasil'],
            ['codigo_banco' => '748', 'nome' => 'Sicredi'],
            ['codigo_banco' => '749', 'nome' => 'Brmsantil S/A],'],
            ['codigo_banco' => '750', 'nome' => 'Banco Republic National Of New York (Bra)'],
            ['codigo_banco' => '751', 'nome' => 'Dresdner Bank Lateinamerika-Brasil S/A'],
            ['codigo_banco' => '752', 'nome' => 'Banco Banque Nationale de Paris Brasil S/A'],
            ['codigo_banco' => '753', 'nome' => 'Banco Comercial Uruguai S/A.'],
            ['codigo_banco' => '755', 'nome' => 'Banco Merrill Lynch S/A'],
            ['codigo_banco' => '756', 'nome' => 'Banco Cooperativo do Brasil S/A.'],
            ['codigo_banco' => '757', 'nome' => 'Banco Keb do Brasil S/A.'],
        ];


        Banco::create([
            'codigo_banco' => '000',
            'nome' => 'Sem Banco',
        ]);

        foreach ($bancos as $banco) {
            Banco::create([
                'codigo_banco' => $banco['codigo_banco'],
                'nome' => $banco['nome'],
            ]);
        }
    }
}
